---
- name: This is a playbook makes sure that the hosts in a cluster are started
  hosts: localhost
  gather_facts: False
  tasks:
    - block:
      - include_vars: ../ovirt_Password.yml
      
      - name: Obtain SSO token using username/password creds.
        ovirt_auth:
          url: https://rhvm.internal.croftvillas.com/ovirt-engine/api
          username: admin@internal
          ca_file: ../pki-resource.cer
          password: "{{ ovirt_password }}"


      - name: Collect facts about the RHEV hosts
        ovirt_host_facts:
          auth: "{{ ovirt_auth }}" 

      - name: Output the json structure
        debug:
          var: ovirt_hosts

      - name: Check whether more than one host is running
        set_fact:
          abort_flag: "{{ (ovirt_hosts | json_query(query) | length) > 1 }}"
        vars:
          query: "[?status=='up'].address"
      - name: Print Success
        debug:
          msg: "Yay Success"
        when:  abort_flag 

      always:
      - name: Always revoke the SSO token
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
